#!/bin/bash
 
#Program to output a system information page
 
title="System Information Report For $HOSTNAME"
 
echo "<html>
        <head>
                <title>$title</title>
        </head>
        <body>
                <h1>$title</h1>
        </body>
</html>"
