#!/bin/bash

#Program to output a system information page

title="System Information Report For $HOSTNAME"

echo "<html>
        <head>
                <title>System Information Report</title>
        </head>
        <body>
                <h1>System Information Report</h1>
        </body>
</html>"
